A few comments, attempt to do colors, and renamed output

diff --git a/projects/failure-list b/projects/failure-list
--- a/projects/failure-list
+++ b/projects/failure-list
@@ -9,12 +9,17 @@ RST=projects/GHC-6.6-failures.rst
 PORTAGE=/usr/portage
 ESCAPED_PORTAGE="\\/usr\\/portage"
 
+YELLOW="\033[33m"
+RED="\033[31m"
+NORMAL="\033[0m"
+
 if [[ "$1" == "--help" ]]; then
   echo usage: $0
   echo [123] package
   echo 1. X means the package is present in $RST, otherwise not present
-  echo 2. P means the package is present in $PORTAGE
-  echo 2. C means the package is only present in $PORTAGE, not in the ovelay
+  echo 2.   empty means the package is only present in the overlay
+  echo 2. B means the package is present both in the overlay and in $PORTAGE
+  echo 2. P means the package is only present in $PORTAGE, not in the ovelay
   echo 3. D means the package in the overlay is different from the $PORTAGE version
   exit 0
 fi
@@ -25,12 +30,14 @@ for EBUILD in ${EBUILDS}; do
   echo -n "["
   grep --quiet "^${PKG}" "${RST}"
   if [[ $? -eq 0 ]]; then
+    # present in the failure list
     echo -n "X"
   else
     echo -n " "
   fi
   if [[ -f "${PORTAGE}/${EBUILD}" ]]; then
-    echo -n "P"
+    # exists both in the overlay and portage
+    echo -n "B"
 
     #ignore comment lines
     T1=$( mktemp )
@@ -43,8 +50,9 @@ for EBUILD in ${EBUILDS}; do
     sed -e "s/#.*//" -i "${T2}"
 
     diff -q "${T1}" "${T2}" > /dev/null
-   if [[ $? -eq 1 ]]; then
-      echo -n "D"
+    if [[ $? -eq 1 ]]; then
+      # file in overlay and portage differs
+      echo -n -e "${RED}D${NORMAL}"
     else
       echo -n " "
     fi
@@ -62,17 +70,22 @@ NAMES=$( echo "${EBUILDS}" | cut -d '/' -f 1,2 | uniq | sort )
 
 for NAME in ${NAMES}; do
   if [[ ! -d "${PORTAGE}/${NAME}" ]]; then
+    # the packages does not exist in portage
     continue
   fi
+
+  # find packages in portage 
   for CVSNAME in $( find "${PORTAGE}/${NAME}" -name "*.ebuild" ); do
     SHORT_CVSNAME=$( echo "$CVSNAME" | sed -e "s/${ESCAPED_PORTAGE}\///" )
     if [[ -f "${SHORT_CVSNAME}" ]]; then
+      # file alreay exist in overlay, which means we've already tested it
       continue
     fi
     PKG=$( echo "${SHORT_CVSNAME}" | sed -e s/.ebuild// | cut -d '/' -f 1,3 )
     echo -n "["
     grep --quiet "^${PKG}" "${RST}"
     if [[ $? -eq 0 ]]; then
+      # package present in failure list
       echo -n "X"
     else
       echo -n " "
